'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.appInit = exports.createWindow = undefined;

var _electron = require('electron');

var createWindow = exports.createWindow = function createWindow(url) {
  return function (win) {
    win = new _electron.BrowserWindow({
      width: 800,
      height: 600
    });
    win.on('closed', function () {
      return win = null;
    });
    if (url != null) {
      return win.loadURL(url);
    } else {
      return new Error("No URL was passed to open");
    }
  }(void 0);
}; // Generated by CoffeeScript 2.0.2
/*
 * riki-browser.coffee
 * @author Sidharth Mishra
 * @description Adding browser support to rikimaru
 * @created Mon Nov 20 2017 20:46:05 GMT-0800 (PST)
 * @last-modified Mon Nov 20 2017 20:46:05 GMT-0800 (PST)
 */
var appInit = exports.appInit = function appInit() {
  return _electron.app.on('activate', function () {
    if (typeof win === "undefined" || win === null) {
      return createWindow();
    }
  });
};